name: continuous integration pipeline

on:
  push:
    branches:
      - test
    paths-ignore:
      - 'k8s'
      - '**/*.md'
      - '.gitignore'
permissions:
  contents: read

jobs:

  secret-scans:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Download dependencies
        run: go mod download

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        # env:
        #   GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}

  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Download dependencies
        run: go mod download
      
      - name: Build
        run: go build ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.2

  vulerability-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Go 1.25
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Download dependencies
        run: go mod download

      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...


  image-build:
    needs: [secret-scans, vulerability-scan]
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: harshitrajsinha/socials
      IMAGE_TAG: ${{ github.sha }}

    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG -f docker/Dockerfile .

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Analyze for critical and high CVEs
        uses: docker/scout-action@v1
        with:
          command: cves
          image: $IMAGE_NAME:$IMAGE_TAG
          sarif-file: sarif.output.json
          summary: true

      - name: Upload SARIF result
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sarif.output.json
      
